/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinRouteImport } from './routes/join'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as TeamFilesRouteImport } from './routes/team.files'
import { Route as TeamProfileRouteImport } from './routes/team.profile'
import { Route as TeamResetPasswordRouteImport } from './routes/team.reset-password'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthPasswordRouteImport } from './routes/api/auth/password'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiTeamActivityRouteImport } from './routes/api/team/activity'
import { Route as ApiTeamAnnouncementsRouteImport } from './routes/api/team/announcements'
import { Route as ApiTeamAttendanceRouteImport } from './routes/api/team/attendance'
import { Route as ApiTeamDownloadRouteImport } from './routes/api/team/download'
import { Route as ApiTeamFilesRouteImport } from './routes/api/team/files'
import { Route as ApiTeamLeavesRouteImport } from './routes/api/team/leaves'
import { Route as ApiTeamMembersRouteImport } from './routes/api/team/members'
import { Route as ApiTeamNotesRouteImport } from './routes/api/team/notes'
import { Route as ApiTeamProfileRouteImport } from './routes/api/team/profile'
import { Route as ApiTeamShareRouteImport } from './routes/api/team/share'
import { Route as ApiTeamTasksRouteImport } from './routes/api/team/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamFilesRoute = TeamFilesRouteImport.update({
  id: '/team/files',
  path: '/team/files',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamProfileRoute = TeamProfileRouteImport.update({
  id: '/team/profile',
  path: '/team/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamResetPasswordRoute = TeamResetPasswordRouteImport.update({
  id: '/team/reset-password',
  path: '/team/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPasswordRoute = ApiAuthPasswordRouteImport.update({
  id: '/api/auth/password',
  path: '/api/auth/password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamActivityRoute = ApiTeamActivityRouteImport.update({
  id: '/api/team/activity',
  path: '/api/team/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamAnnouncementsRoute = ApiTeamAnnouncementsRouteImport.update({
  id: '/api/team/announcements',
  path: '/api/team/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamAttendanceRoute = ApiTeamAttendanceRouteImport.update({
  id: '/api/team/attendance',
  path: '/api/team/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamDownloadRoute = ApiTeamDownloadRouteImport.update({
  id: '/api/team/download',
  path: '/api/team/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamFilesRoute = ApiTeamFilesRouteImport.update({
  id: '/api/team/files',
  path: '/api/team/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamLeavesRoute = ApiTeamLeavesRouteImport.update({
  id: '/api/team/leaves',
  path: '/api/team/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamMembersRoute = ApiTeamMembersRouteImport.update({
  id: '/api/team/members',
  path: '/api/team/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamNotesRoute = ApiTeamNotesRouteImport.update({
  id: '/api/team/notes',
  path: '/api/team/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamProfileRoute = ApiTeamProfileRouteImport.update({
  id: '/api/team/profile',
  path: '/api/team/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamShareRoute = ApiTeamShareRouteImport.update({
  id: '/api/team/share',
  path: '/api/team/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamTasksRoute = ApiTeamTasksRouteImport.update({
  id: '/api/team/tasks',
  path: '/api/team/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/team/files': typeof TeamFilesRoute
  '/team/profile': typeof TeamProfileRoute
  '/team/reset-password': typeof TeamResetPasswordRoute
  '/team/': typeof TeamIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/team/activity': typeof ApiTeamActivityRoute
  '/api/team/announcements': typeof ApiTeamAnnouncementsRoute
  '/api/team/attendance': typeof ApiTeamAttendanceRoute
  '/api/team/download': typeof ApiTeamDownloadRoute
  '/api/team/files': typeof ApiTeamFilesRoute
  '/api/team/leaves': typeof ApiTeamLeavesRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/api/team/notes': typeof ApiTeamNotesRoute
  '/api/team/profile': typeof ApiTeamProfileRoute
  '/api/team/share': typeof ApiTeamShareRoute
  '/api/team/tasks': typeof ApiTeamTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/team/files': typeof TeamFilesRoute
  '/team/profile': typeof TeamProfileRoute
  '/team/reset-password': typeof TeamResetPasswordRoute
  '/team': typeof TeamIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/team/activity': typeof ApiTeamActivityRoute
  '/api/team/announcements': typeof ApiTeamAnnouncementsRoute
  '/api/team/attendance': typeof ApiTeamAttendanceRoute
  '/api/team/download': typeof ApiTeamDownloadRoute
  '/api/team/files': typeof ApiTeamFilesRoute
  '/api/team/leaves': typeof ApiTeamLeavesRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/api/team/notes': typeof ApiTeamNotesRoute
  '/api/team/profile': typeof ApiTeamProfileRoute
  '/api/team/share': typeof ApiTeamShareRoute
  '/api/team/tasks': typeof ApiTeamTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/team/files': typeof TeamFilesRoute
  '/team/profile': typeof TeamProfileRoute
  '/team/reset-password': typeof TeamResetPasswordRoute
  '/team/': typeof TeamIndexRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/password': typeof ApiAuthPasswordRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/team/activity': typeof ApiTeamActivityRoute
  '/api/team/announcements': typeof ApiTeamAnnouncementsRoute
  '/api/team/attendance': typeof ApiTeamAttendanceRoute
  '/api/team/download': typeof ApiTeamDownloadRoute
  '/api/team/files': typeof ApiTeamFilesRoute
  '/api/team/leaves': typeof ApiTeamLeavesRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/api/team/notes': typeof ApiTeamNotesRoute
  '/api/team/profile': typeof ApiTeamProfileRoute
  '/api/team/share': typeof ApiTeamShareRoute
  '/api/team/tasks': typeof ApiTeamTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/team/files'
    | '/team/profile'
    | '/team/reset-password'
    | '/team/'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/password'
    | '/api/public/chat'
    | '/api/team/activity'
    | '/api/team/announcements'
    | '/api/team/attendance'
    | '/api/team/download'
    | '/api/team/files'
    | '/api/team/leaves'
    | '/api/team/members'
    | '/api/team/notes'
    | '/api/team/profile'
    | '/api/team/share'
    | '/api/team/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/team/files'
    | '/team/profile'
    | '/team/reset-password'
    | '/team'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/password'
    | '/api/public/chat'
    | '/api/team/activity'
    | '/api/team/announcements'
    | '/api/team/attendance'
    | '/api/team/download'
    | '/api/team/files'
    | '/api/team/leaves'
    | '/api/team/members'
    | '/api/team/notes'
    | '/api/team/profile'
    | '/api/team/share'
    | '/api/team/tasks'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/team/files'
    | '/team/profile'
    | '/team/reset-password'
    | '/team/'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/password'
    | '/api/public/chat'
    | '/api/team/activity'
    | '/api/team/announcements'
    | '/api/team/attendance'
    | '/api/team/download'
    | '/api/team/files'
    | '/api/team/leaves'
    | '/api/team/members'
    | '/api/team/notes'
    | '/api/team/profile'
    | '/api/team/share'
    | '/api/team/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  TeamFilesRoute: typeof TeamFilesRoute
  TeamProfileRoute: typeof TeamProfileRoute
  TeamResetPasswordRoute: typeof TeamResetPasswordRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthPasswordRoute: typeof ApiAuthPasswordRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiTeamActivityRoute: typeof ApiTeamActivityRoute
  ApiTeamAnnouncementsRoute: typeof ApiTeamAnnouncementsRoute
  ApiTeamAttendanceRoute: typeof ApiTeamAttendanceRoute
  ApiTeamDownloadRoute: typeof ApiTeamDownloadRoute
  ApiTeamFilesRoute: typeof ApiTeamFilesRoute
  ApiTeamLeavesRoute: typeof ApiTeamLeavesRoute
  ApiTeamMembersRoute: typeof ApiTeamMembersRoute
  ApiTeamNotesRoute: typeof ApiTeamNotesRoute
  ApiTeamProfileRoute: typeof ApiTeamProfileRoute
  ApiTeamShareRoute: typeof ApiTeamShareRoute
  ApiTeamTasksRoute: typeof ApiTeamTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/files': {
      id: '/team/files'
      path: '/team/files'
      fullPath: '/team/files'
      preLoaderRoute: typeof TeamFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/profile': {
      id: '/team/profile'
      path: '/team/profile'
      fullPath: '/team/profile'
      preLoaderRoute: typeof TeamProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/reset-password': {
      id: '/team/reset-password'
      path: '/team/reset-password'
      fullPath: '/team/reset-password'
      preLoaderRoute: typeof TeamResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/password': {
      id: '/api/auth/password'
      path: '/api/auth/password'
      fullPath: '/api/auth/password'
      preLoaderRoute: typeof ApiAuthPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/activity': {
      id: '/api/team/activity'
      path: '/api/team/activity'
      fullPath: '/api/team/activity'
      preLoaderRoute: typeof ApiTeamActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/announcements': {
      id: '/api/team/announcements'
      path: '/api/team/announcements'
      fullPath: '/api/team/announcements'
      preLoaderRoute: typeof ApiTeamAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/attendance': {
      id: '/api/team/attendance'
      path: '/api/team/attendance'
      fullPath: '/api/team/attendance'
      preLoaderRoute: typeof ApiTeamAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/download': {
      id: '/api/team/download'
      path: '/api/team/download'
      fullPath: '/api/team/download'
      preLoaderRoute: typeof ApiTeamDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/files': {
      id: '/api/team/files'
      path: '/api/team/files'
      fullPath: '/api/team/files'
      preLoaderRoute: typeof ApiTeamFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/leaves': {
      id: '/api/team/leaves'
      path: '/api/team/leaves'
      fullPath: '/api/team/leaves'
      preLoaderRoute: typeof ApiTeamLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/members': {
      id: '/api/team/members'
      path: '/api/team/members'
      fullPath: '/api/team/members'
      preLoaderRoute: typeof ApiTeamMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/notes': {
      id: '/api/team/notes'
      path: '/api/team/notes'
      fullPath: '/api/team/notes'
      preLoaderRoute: typeof ApiTeamNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/profile': {
      id: '/api/team/profile'
      path: '/api/team/profile'
      fullPath: '/api/team/profile'
      preLoaderRoute: typeof ApiTeamProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/share': {
      id: '/api/team/share'
      path: '/api/team/share'
      fullPath: '/api/team/share'
      preLoaderRoute: typeof ApiTeamShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/tasks': {
      id: '/api/team/tasks'
      path: '/api/team/tasks'
      fullPath: '/api/team/tasks'
      preLoaderRoute: typeof ApiTeamTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  TeamFilesRoute: TeamFilesRoute,
  TeamProfileRoute: TeamProfileRoute,
  TeamResetPasswordRoute: TeamResetPasswordRoute,
  TeamIndexRoute: TeamIndexRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthPasswordRoute: ApiAuthPasswordRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiTeamActivityRoute: ApiTeamActivityRoute,
  ApiTeamAnnouncementsRoute: ApiTeamAnnouncementsRoute,
  ApiTeamAttendanceRoute: ApiTeamAttendanceRoute,
  ApiTeamDownloadRoute: ApiTeamDownloadRoute,
  ApiTeamFilesRoute: ApiTeamFilesRoute,
  ApiTeamLeavesRoute: ApiTeamLeavesRoute,
  ApiTeamMembersRoute: ApiTeamMembersRoute,
  ApiTeamNotesRoute: ApiTeamNotesRoute,
  ApiTeamProfileRoute: ApiTeamProfileRoute,
  ApiTeamShareRoute: ApiTeamShareRoute,
  ApiTeamTasksRoute: ApiTeamTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
